### ISSUE TITLE
Need a way to prevent @click event

### ISSUE THREAD

**Issue by Laurensdc** [FeliciousX/vue-directive-long-press#11]
At the moment, it doesn't seem possible to combine `@click` with `@long-press-start`.
Therefor, every time the long press event fires, the click event also fires.

Need something like `@long-press-start.prevent` where the click event won't fire.

**Comment by kiyui** [comment]
Hi @Laurensdc, this directive makes use of [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) so it wouldn't make much sense of us to provide this functionality :smile: 

Also, nothing would prevent a user from just doing `@pointerdown.prevent` if they needed to do that either~
