### ISSUE TITLE
possible to add event

### ISSUE THREAD

**Issue by ghost** [FeliciousX/vue-directive-long-press#21]
in vue i want to get the mouse (or finger) position of the long press. i wanted to do this by adding the event, but this gives undefined:

`
@long-press-start="onLongPressStart(e)"

onLongPressStart (e) {
    console.log(e);
},
`

**Comment by kiyui** [comment]
You can see the custom events now added to the demo: https://vue-directive-long-press-demo.stackblitz.io/

As for getting the pointer position, you're better off adding an additional `pointerdown` event :smile:
